### PR TITLE
Bring in upstream changes

### PR DESCRIPTION
**Pull request by alexmuller**
There are 3 of my commits at the end of this branch which make changes based on the upstream commits.

### CODE REVIEW

**Comment by ajlanghorn** [comment]
@alexmuller Thanks for the contribution! Is this just a rebase from the parent repository's master branch on to this one? All looks a-okay to me.

**Comment by mattbostock** [comment]
LGTM. :+1:

Only one suggestion - rather than removing the coverage report by commenting it out, could it just be removed? We can always revert the commit later.

You should submit b29b5fd680586df8ea1cd2a7fd00cd632241b83c upstream if you haven't done so already.

**Comment by alexmuller** [comment]
Yep, this just pulls in the changes that have been made to the upstream.

> rather than removing the coverage report by commenting it out, could it just be removed? We can always revert the commit later.

We can do that. I think @dcarley and I did that so that we remember to bring it back in, but it'd be good to check with him too.

> You should submit b29b5fd upstream if you haven't done so already.

The CONTRIBUTING file that's upstream has diverged from ours quite significantly, but I'll see about the changes to the README.

**Comment by mattbostock** [comment]
> The CONTRIBUTING file that's upstream has diverged from ours quite significantly, but I'll see about the changes to the README.

It's not that important, but I like the removal of the rake task list :+1:

**Comment by dcarley** [comment]
Looks like this it OK to go..

**Pull request merged**
